[package]
name = "mathing-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {workspace = true}
tonic = {workspace = true}
tonic-prost = {workspace = true}
prost = {workspace = true}

[build-dependencies]
tonic-prost-build = {workspace = true}
