name: Mathing CI
on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: arc-mathing
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Install nix deps
      run: |
        sudo apt-get update
        sudo apt-get install xz-utils
    - name: Install nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
    - name: Test shell environment
      run: nix develop . --command enterTest
    - name: Initialize db and migration
      run: nix develop . --command just init_db
    - name: Run tests and build
      run: nix develop . --command just

  lint:
    runs-on: arc-mathing
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Install nix deps
      run: |
        sudo apt-get update
        sudo apt-get install xz-utils
    - name: Install nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
    - name: Test shell environment
      run: nix develop .#ciLint --command enterTest
    - name: Run lint
      run: nix develop .#ciLint --command just lint
