name: Mathing CI
on:
  pull_request:
    branches:
    - main

jobs:
  lint:
    runs-on: arc-mathing
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install nix deps
      run: |
        sudo apt-get update
        sudo apt-get install xz-utils
    - name: Install nix
      uses: cachix/install-nix-action@v31
    - name: Enter dev shell
      run: nix develop .#ci
    - name: Run lint
      run: just lint
